### ISSUE TITLE
Put latest version in cargo

### ISSUE THREAD

**Issue by jes** [eholk/rust-stl#6]
There was a commit 4 years ago that made the triangle coordinates non-private, but it still seems to not be in cargo. I wonder how hard that would be to fix?

**Comment by eholk** [comment]
Hey, thanks for reaching out!

I just pushed a new version, 0.2.1, up to crates.io, so this should be fixed now.

I'm actually impressed the code still works with modern Rust, since I haven't touched it in a few years. It looks like there are some minor cleanups to do though, so I'll try to get those up before long too. These shouldn't affect usage though.

**Comment by jes** [comment]
Great stuff, many thanks!
